name: Security Tests
on:
  push:
  pull_request:
jobs:
  hawkscan:
    name: StackHawk DAST
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run the Vuln Java Containers
        run: docker-compose up -d
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        continue-on-error: false
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml
          codeScanningAlerts: true
          githubToken: ${{ github.token }}

  snyk-code-scan:
    name: Snyk Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: |
            "--severity-threshold=high"
            "--sarif-file-output=snyk-code.sarif"
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-code.sarif

    snyk-sca-scan:
      name: Snyk Code Scan
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v2
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/gradle@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test
            args: |
              "--severity-threshold=high"
              "--sarif-file-output=snyk-sca.sarif"
        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: snyk-sca.sarif
